### PR TITLE
CI updated with MPW5 designs

### PR DESCRIPTION
**Pull request by vijayank88**
Following MPW5 designs added to CI:
```
ChirstmasTreeController
logic_bist LBIST_mbist_top1
logic_bist LBIST_mbist_top2
mpw5_microwatt Microwatt_FP_DFFRFile
mpw5_microwatt Microwatt_multiply_add
riscduino rd_yifive
riscduino riscduino_wrapper
riscduino_dcore rdd_ycr2_iconnect
riscduino_qcore rdq_pinmux
riscduino_qcore rdq_qspim_top
riscduino_qcore rdq_uart_i2cm_usb_spi_top
riscduino_qcore rdq_ycr4_iconnect
riscduino_qcore rdq_ycr_core_top
riscduino_qcore rdq_ycr_intf
rng_chaos
```

### CODE REVIEW

**Comment by vijayank88** [comment]
@vvbandeira 
Jenkinsfile split into individual MPW shuttle name and its design list as follows:
```
   mpw-2.Jenkinsfile
   mpw-3.Jenkinsfile
   mpw-4.Jenkinsfile
   mpw-5.Jenkinsfile

```

**Comment by vvbandeira** [comment]
@vijayank88 thanks. You can also remove the old Jenkinsfile. If you notice that a given shuttle is getting too big, you can split it further (`mpw-X-part-1.Jenkinsfile`, etc). Just let me know about the change.

**Comment by vijayank88** [comment]
> @vijayank88 thanks. You can also remove the old Jenkinsfile. If you notice that a given shuttle is getting too big, you can split it further (`mpw-X-part-1.Jenkinsfile`, etc). Just let me know about the change.

Do you want me remove `Jenkinsfile` and push again?

**Comment by vijayank88** [comment]
> > Do you want me remove `Jenkinsfile` and push again?
> 
> Yes, please. That will no longer be used. Is better to remove it now to avoid confusion in the future.

Removed old Jenkinsfile, now only mpw-*.Jenkinsfile exist

**Pull request merged**
