### PR TITLE
OL tag updated to 2022.03.02_02.59.05

### PR DESCRIPTION
**Pull request by vijayank88**
Signed-off-by: vijayank88 <paruthi143@gmail.com>

### CODE REVIEW

**Comment by vijayank88** [comment]
Flow failed only for yonga-lz4-decoder with LVS error. All other designs passed successfully.
```
[2022-03-01T11:01:18.481Z] Circuit 1 contains 10157 devices, Circuit 2 contains 10124 devices. *** MISMATCH ***
[2022-03-01T11:01:18.481Z] Circuit 1 contains 10255 nets,    Circuit 2 contains 10249 nets. *** MISMATCH ***
[2022-03-01T11:01:18.481Z] 
[2022-03-01T11:01:54.904Z] Result: Netlists do not match.
[2022-03-01T11:01:54.904Z] Logging to file "/openlane/designs/yonga-lz4-decoder/runs/RUN_2022.03.01_10.44.36/logs/finishing/35-user_proj_example.lef.log" disabled
[2022-03-01T11:01:54.904Z] LVS Done.
[2022-03-01T11:01:54.904Z] LVS reports:
[2022-03-01T11:01:54.904Z]     net count difference = 6
[2022-03-01T11:01:54.904Z]     device count difference = 33
[2022-03-01T11:01:54.904Z]     unmatched nets = 797
[2022-03-01T11:01:54.904Z]     unmatched devices = 130
[2022-03-01T11:01:54.904Z]     unmatched pins = 0
[2022-03-01T11:01:54.904Z]     property failures = 0
[2022-03-01T11:01:54.904Z] 
[2022-03-01T11:01:54.904Z] Total errors = 966
[2022-03-01T11:01:55.389Z] [ERROR]: There are LVS errors in the design according to Netgen LVS.
[2022-03-01T11:01:55.389Z] [INFO]: Calculating Runtime From the Start...
[2022-03-01T11:01:55.389Z] [INFO]: Generating Final Summary Report...
[2022-03-01T11:02:00.359Z] [INFO]: Design Name: user_proj_example
[2022-03-01T11:02:00.359Z] Run Directory: /openlane/designs/yonga-lz4-decoder/runs/RUN_2022.03.01_10.44.36
[2022-03-01T11:02:00.359Z] Source not found.
[2022-03-01T11:02:00.359Z] ----------------------------------------
[2022-03-01T11:02:00.359Z] 
[2022-03-01T11:02:00.359Z] LVS Summary:
[2022-03-01T11:02:00.359Z] Source: /openlane/designs/yonga-lz4-decoder/runs/RUN_2022.03.01_10.44.36/logs/finishing/35-user_proj_example.lvs.lef.log
[2022-03-01T11:02:00.359Z]     net count difference = 6
[2022-03-01T11:02:00.359Z]     unmatched nets = 797
[2022-03-01T11:02:00.359Z] Total errors = 966
[2022-03-01T11:02:00.359Z] ----------------------------------------
```
@dralabeing  FYI

**Comment by vijayank88** [comment]
@dralabeing FYI
As I mentioned earlier randomly `yonga_lz4_decoder` fails with hold violations.
Commit [bf2412f](https://github.com/The-OpenROAD-Project/OpenLane-MPW-CI/pull/8/commits/bf2412f02af20191f2c554624811d90c2fcf97e9) successfully passed with OL tag.
Same OL tag today got failed during CI.

@vvbandeira How to download `yonga-lz4-decoder` project from CI repo for debugging the issue?

**Comment by vijayank88** [comment]
@vvbandeira [768649a](https://github.com/The-OpenROAD-Project/OpenLane-MPW-CI/pull/8/commits/768649a19a2f7f1ed5255d8a0ee326c77b4f3eea)
The design which got failed in CI for the commit `soric_soc` while I ran locally no hold violations. See the log below:
```
Antenna Summary:
Source: /openlane/designs/soric_soc/runs/RUN_2022.03.05_10.03.37/reports/finishing/antenna.rpt
Number of pins violated: 204
Number of nets violated: 180
[INFO]: check full report here: /openlane/designs/soric_soc/runs/RUN_2022.03.05_10.03.37/reports/final_summary_report.csv
[WARNING]: There are max slew violations in the design at the typical corner. Please refer to /openlane/designs/soric_soc/runs/RUN_2022.03.05_10.03.37/reports/routing/28-parasitics_sta.slew.rpt
[INFO]: There are no hold violations in the design at the typical corner.
[INFO]: There are no setup violations in the design at the typical corner.
[SUCCESS]: Flow complete.
[INFO]: Note that the following warnings have been generated:
[WARNING]: There are max slew violations in the design at the typical corner. Please refer to /openlane/designs/soric_soc/runs/RUN_2022.03.05_10.03.37/reports/routing/28-parasitics_sta.slew.rpt
```
Based on exception we can ignore the `soric_soc` failure and merge the commit and move on.

@dralabeing share your view please

**Comment by vvbandeira** [comment]
> @dralabeing FYI As I mentioned earlier randomly `yonga_lz4_decoder` fails with hold violations. Commit [bf2412f](https://github.com/The-OpenROAD-Project/OpenLane-MPW-CI/pull/8/commits/bf2412f02af20191f2c554624811d90c2fcf97e9) successfully passed with OL tag. Same OL tag today got failed during CI.
> 
> @vvbandeira How to download `yonga-lz4-decoder` project from CI repo for debugging the issue?

You can find the files here:
https://jenkins.openroad.tools/job/OpenLane-MPW-CI-Public/job/PR-8-merge/4/artifact/OpenLane-2022.03.03_02.36.44/designs/yonga-lz4-decoder/


> @vvbandeira [768649a](https://github.com/The-OpenROAD-Project/OpenLane-MPW-CI/pull/8/commits/768649a19a2f7f1ed5255d8a0ee326c77b4f3eea) The design which got failed in CI for the commit `soric_soc` while I ran locally no hold violations. See the log below:
> 
> ```
> Antenna Summary:
> Source: /openlane/designs/soric_soc/runs/RUN_2022.03.05_10.03.37/reports/finishing/antenna.rpt
> Number of pins violated: 204
> Number of nets violated: 180
> [INFO]: check full report here: /openlane/designs/soric_soc/runs/RUN_2022.03.05_10.03.37/reports/final_summary_report.csv
> [WARNING]: There are max slew violations in the design at the typical corner. Please refer to /openlane/designs/soric_soc/runs/RUN_2022.03.05_10.03.37/reports/routing/28-parasitics_sta.slew.rpt
> [INFO]: There are no hold violations in the design at the typical corner.
> [INFO]: There are no setup violations in the design at the typical corner.
> [SUCCESS]: Flow complete.
> [INFO]: Note that the following warnings have been generated:
> [WARNING]: There are max slew violations in the design at the typical corner. Please refer to /openlane/designs/soric_soc/runs/RUN_2022.03.05_10.03.37/reports/routing/28-parasitics_sta.slew.rpt
> ```
> 
> Based on exception we can ignore the `soric_soc` failure and merge the commit and move on.

We cannot just ignore if the CI is red, this need to be fixed or removed from CI.

**Comment by vijayank88** [comment]
@vvbandeira 
While I test locally with `./scripts/run-design.sh soric_soc` or `yonga-lz4-decoder` designs not facing hold violations or LVS mismatch.
But during CI at different runs these issue coming.
What will be the root cause?

**Comment by vvbandeira** [comment]
@vijayank88 do you know if the OL tag we use contains the commits from this PR?
https://github.com/The-OpenROAD-Project/OpenROAD/pull/1681/commits

**Comment by vijayank88** [comment]
> @vijayank88 do you know if the OL tag we use contains the commits from this PR? https://github.com/The-OpenROAD-Project/OpenROAD/pull/1681/commits

Yes @vvbandeira currently OL tag uses this OpenROAD commit: 944855835623e651e7b9c7c50efcce1fb04b4fee
https://github.com/The-OpenROAD-Project/OpenROAD/commit/944855835623e651e7b9c7c50efcce1fb04b4fee
https://github.com/The-OpenROAD-Project/OpenLane/blob/master/dependencies/tool_metadata.yml

**Comment by vijayank88** [comment]
@vvbandeira  then I'll revert my OL tag to `2022.03.02_02.59.05` this. Will check CI status?

**Comment by vijayank88** [comment]
@vvbandeira Please approve and merge it. Thanks

**Review by vvbandeira — APPROVED** [review]

**Pull request merged**
